### ISSUE TITLE
Improve embedded login UX when credential already present

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit#179]
Right now, if you sign into an embedded prompt when you're already signed in, the popup window will be able to read the credential, and then it'll immediately close, which is jarring and surprising. We should improve this UX (maybe a "Continue with x@y.com?")

**Comment by kirkbyo** [comment]
I am looking to take this on but I am having trouble reproducing the issue. Here are the steps I have tried:

1. Fresh DB (no users), spin up the web-components test page (`localhost:5000`) and complete the first set of prompts.
2. After completing the prompts, create a new user.
3. Complete the second test. This is where I would have expected the "flash" of the auth window to appear, but I did not see it.
4. Open a new browser and complete the third test. Sign into the user created during step 2. 

[Demo of me walking through the steps above](https://www.loom.com/share/4b71a6dde5f245f4badedfdf4d36d615)

Let me know if I am missing something or miss-understanding the issue.

**Comment by andymatuschak** [comment]
I really should have included reproduction steps; I'm sorry! The problem occurs when an embedded review area (which is a third-party iframe) is prevented from accessing the stored credentials, while a popup (a first-party window) is permitted. When this occurs depends on your browser and security settings, but in general it'll happen if you _move between_ sites which use Orbit, and in some circumstances between sessions on the same site.

Unfortunately, this can be tricky to see locally because `localhost:5000` and `localhost:19006` are considered the same domain (at least by Chrome), and so the iframe isn't sandboxed like a third party.

1. Set Chrome to block third-party cookies.
2. Fresh DB (no users), spin up the web-components test page but visit http://127.0.0.1:5000 instead of `localhost:5000` and complete the first set of prompts.
3. After completing the prompts, create a new user. At this point, other review areas on the same page should use that credential.
4. Refresh the page. Your progress should not be loaded.
5. Complete the first review area again. Enter `test@test.com` into the email field.
6. You should see the auth popup appear and immediately disappear.

Safari exhibits the same behavior with its _default_ settings (i.e. without third-party cookie blocking set) if you navigate to two different embedding hosts. Using 127.0.0.1 and your network IP (e.g. 192.168.0.167) might be enough to exhibit the issue.
