### ISSUE TITLE
Embedded Orbit contexts (and possibly /review) don’t load when uBlock Origin is enabled

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/orbit#201]
I've gotten a few reports from users that when uBlock Origin is installed, the embedded prompts are empty. And I've gotten one report that `/review` also fails to load! I haven't verified either, and I'm not sure why the latter would be. The former is perhaps unsurprising, since embedded iframe contexts are often quite locked down.

We should understand what's happening here and either adapt what we're doing to the constrained environment or at least warn the user.

**Comment by qubist** [comment]
I'm not sure if this is relevant, but https://withorbit.com doesn't load when I have uBlock Origin enabled. (If there's a better place for this report I'll move or delete it)

**Browser:** Firefox 88.0 (64-bit)
**OS:** macOS 11.0.1 (20B29)

**Comment by andymatuschak** [comment]
Yep, that's probably related, thanks!
