### ISSUE TITLE
yarn run web crashes

### ISSUE THREAD

**Issue by nafizh** [andymatuschak/orbit#205]
When trying to run the web app on browser, it shows the following error:

>Failed to compile.
/home/nafizh/orbit/packages/app/src/embedded/useInitialPromptStates.ts
Module not found: Can't resolve '@withorbit/api-client' in '/home/nafizh/orbit/packages/app/src/embedded'
(node:20833) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
raven@2.6.3 alert: failed to send exception to sentry: Connection timed out on request to sentry.io
Error: ENOENT: no such file or directory, stat '/home/nafizh/.steampath'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

What might be the problem here?

System:
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by andymatuschak** [comment]
Ah. I expect the problem is that the libraries aren't built. Try running `yarn build` in the root of the project then trying again and letting me know what happens?

I'll add a note about this to the README.

**Comment by nafizh** [comment]
Yes, that solves the problem. Thanks. Closing this.
