### ISSUE TITLE
Basic math symbols missing

### ISSUE THREAD

**Issue by riceissa** [andymatuschak/orbit#297]
**Describe the bug**

Starting several months ago, I noticed that the normal LaTeX font is no longer used for math expressions, and this often breaks math expressions because of missing fonts. For example:

![image](https://github.com/andymatuschak/orbit/assets/1450515/b5254eed-6bbc-43ed-81e8-a94be95f7526)

Here a "not equal" symbol is expected.

**To Reproduce**
1. Add a card containing some non-trivial LaTeX symbols, such as `\ne`.
2. View the card.
(You can see an example of this at https://riceissa.github.io/tao-analysis-flashcards/sections/peano-axioms.html )

**Expected behavior**
The missing symbols should be provided or the default LaTeX font containing all the symbols should be used.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 126.0 (64-bit)

**Comment by andymatuschak** [comment]
Ack, sorry!! Absorbed in essay writing, but will look at this soon.

**Comment by andymatuschak** [comment]
Truly, this is one of those unsettling instances in which I'm not sure how this *ever* worked properly. Thank you for pointing it out!

**Comment by riceissa** [comment]
I am still having this problem. The Firefox console says "downloadable font: rejected by sanitizer". Not sure if this is an Orbit problem or a Firefox problem, but it doesn't seem to happen on other websites.

![image](https://github.com/user-attachments/assets/fe7f0b5e-cf86-498c-b5cb-6113c233839f)

**Comment by andymatuschak** [comment]
Very sorry about that, Issa. I was able to reproduce the issue; I've fixed it and verified that your Peano axiom cards render properly in Firefox. Please do let me know if you're still seeing a problem.

**Comment by riceissa** [comment]
Thank you, Andy! It seems to be working for me as well.
